# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 17:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, 'banned'), (1, 'member'), (2, 'moderator'), (3, 'admin')], default=1)),
            ],
            options={
                'permissions': (('ban_member', 'Can ban members'),),
            },
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='repo-name', max_length=255, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, default='repo-name', unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(null=True)),
                ('description_html', models.TextField(editable=False, null=True)),
                ('user', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='repo_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'repos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ownership',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='django_git_tinymce.Repo'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_ownership_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_git_tinymce.Repo'),
        ),
        migrations.AlterUniqueTogether(
            name='ownership',
            unique_together=set([('repo', 'user')]),
        ),
    ]
