# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 19:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_git_tinymce', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repo',
            unique_together=set([('user', 'slug')]),
        ),
    ]
