# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_git_tinymce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownership',
            options={'permissions': (('ban_member', 'Can ban members'),)},
        ),
        migrations.AlterModelOptions(
            name='repo',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'repos'},
        ),
        migrations.AddField(
            model_name='ownership',
            name='role',
            field=models.IntegerField(choices=[(0, 'banned'), (1, 'member'), (2, 'moderator'), (3, 'admin')], default=1),
        ),
        migrations.AddField(
            model_name='repo',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repo',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='repo',
            name='description_html',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='repo',
            name='name',
            field=models.CharField(default='repo-name', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='repo',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='repo-name', unique=True),
        ),
        migrations.AddField(
            model_name='repo',
            name='user',
            field=models.ForeignKey(default='auth.User', on_delete=django.db.models.deletion.CASCADE, related_name='repo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership', to='django_git_tinymce.Repo'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_ownership_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ownership',
            unique_together=set([('repo', 'user')]),
        ),
        migrations.RemoveField(
            model_name='repo',
            name='owners',
        ),
        migrations.AlterUniqueTogether(
            name='repo',
            unique_together=set([('user', 'slug')]),
        ),
    ]
