# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 03:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('repos', '0001_initial'), ('repos', '0002_auto_20170624_1751'), ('repos', '0003_remove_repository_owner'), ('repos', '0004_auto_20170625_1600'), ('repos', '0005_repository_owner'), ('repos', '0006_auto_20170625_2216'), ('repos', '0007_auto_20170625_2258'), ('repos', '0008_auto_20170625_2259'), ('repos', '0009_auto_20170625_2303'), ('repos', '0010_remove_repository_admins'), ('repos', '0011_auto_20170627_1542')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('editors', models.ManyToManyField(blank=True, related_name='editors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set([]),
        ),
    ]
