# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0002_auto_20170624_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='owner',
        ),
    ]
