# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0003_forkedrepository'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forkedrepository',
            name='original',
        ),
        migrations.AddField(
            model_name='forkedrepository',
            name='original',
            field=models.ManyToManyField(related_name='original_repo', to='repos.Repository'),
        ),
    ]
