# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0004_auto_20170908_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forkedrepository',
            name='original',
        ),
        migrations.AddField(
            model_name='forkedrepository',
            name='original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_repo', to='repos.Repository'),
        ),
    ]
