# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import repos.models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0005_auto_20170908_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='height',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=repos.models.img_upload_location, width_field='width'),
        ),
        migrations.AddField(
            model_name='repository',
            name='width',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
