# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0005_auto_20170908_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
