# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 02:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repos', '0005_repository_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set([('owner', 'name')]),
        ),
    ]
