# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import repos.models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0007_auto_20170911_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=repos.models.my_awesome_upload_function),
        ),
    ]
