# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 02:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repos', '0007_auto_20170625_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='admins',
            field=models.ManyToManyField(default=1, related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repository',
            name='editors',
            field=models.ManyToManyField(related_name='editors', to=settings.AUTH_USER_MODEL),
        ),
    ]
