# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_remove_tag_repos'),
        ('repos', '0008_auto_20170911_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
    ]
