# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0009_auto_20170625_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='admins',
        ),
    ]
