# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0010_remove_repository_admins'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='repository',
            unique_together=set([]),
        ),
    ]
