# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0010_auto_20170915_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='repos', to='tags.Tag'),
        ),
    ]
