# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taganalytics',
            options={'verbose_name': 'Tag Analytics', 'verbose_name_plural': 'Tag Analytics'},
        ),
    ]
