# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='repos',
        ),
    ]
